get http://localhost:3000/user/

###


get http://localhost:3000/user/63ffd1ae0cc222ccc1a22bd5

###

Post http://localhost:3000/user
Content-Type: application/json

{
        "username" : "salim",
    "password": "labepierre",
    "email": "ril@gmail.com",
    "name": "falafel",
    "surname": "fahlas",
    "phoneNumber": "056585858521",
    "address": "chrea",
    "role": "user" 
}

      
       
###

PATCH   http://localhost:3000/user/63ff44f11e1a55738bbd5e9d
Content-Type: application/json

{
    "name": "imawawal",
    "surname": "gliadiator"
}


###

delete http://localhost:3000/user/63ffcfcd0cc222ccc1a22bc9
Content-Type: application/json

###



// ------- -----------------------request category ------------------------------------


get http://localhost:3000/category/

###


get http://localhost:3000/category/6400698eec14d4cbb8cab14e

###

Post http://localhost:3000/category
Content-Type: application/json

{
    "name": "physics"
    
}

      
       
###

PATCH   http://localhost:3000/category/640069aaec14d4cbb8cab150
Content-Type: application/json

{
    "name": "biographies",
    
}


###

delete http://localhost:3000/category/64006c0c778729c2a4e69f99
Content-Type: application/json



###    
       
// ------- -----------------------request of books------------------------------------


get http://localhost:3000/book/

###


get http://localhost:3000/book/6400b11d6c0faa0892a979ec


###

Post http://localhost:3000/book
Content-Type: application/json

{
    "title" : "hamlet",
    "description": "amour, drame",
    "publishedDate": "1982-01-04",
    "pageCount": 460,
    "author": "shakes peare",
    "copiesCount": 6,
    "aviabilityCount": 6      
}
      
       
###

PATCH   http://localhost:3000/book/6400b1ff6c0faa0892a979f4
Content-Type: application/json

{
    
    "title" : "la drague",
    "description": "comment draguer",
    "publishedDate": "2003-04-14",
    "pageCount": 600,
    "author": "fhilip",
    "copiesCount": 6,
    "aviabilityCount": 6      
    
}


###

delete http://localhost:3000/book/6400ad946c0faa0892a979e6
Content-Type: application/json

###


// ------- -----------------------request of borrowing------------------------------------

get http://localhost:3000/borrowing/

###


get http://localhost:3000/borrowing/640609d6264e7474fac591a6


###

Post http://localhost:3000/borrowing
Content-Type: application/json

{
    "book": "6400af956c0faa0892a979e8",
    "borrower": "63ffd1ae0cc222ccc1a22bd5"
}

###

Post http://localhost:3000/borrowing/return
Content-Type: application/json

{
    "book": "640cb6cb331aa049404851a6",
    "borrower": "63ff44f11e1a55738bbd5e9d"
}
    
       
###

// to replace a borrower 

PATCH   http://localhost:3000/borrowing/640cb7e3331aa049404851ac
Content-Type: application/json

{
    "book" : "6400b1ff6c0faa0892a979f4",
    "borrower": "63ffd1ae0cc222ccc1a22bd5",
    # "date_borrowed": "2023-03-10",
    # "date_returned": "2023-03-11"
       
}


###

// to not be used as it doesn't take into acount bookaviability

delete http://localhost:3000/borrowing/640cb7e3331aa049404851ac
Content-Type: application/json

###


// to not be used as it doesn't take into acount bookaviability